@apiUrl = http://localhost:4321


### Health check
# @name healthCheck
GET {{ apiUrl }}/api/health-check.json


### Generate QR code in SVG
# @name qrSVG
POST {{ apiUrl }}/api/qr/generate
Content-Type: application/json

{
    "url": "https://github.com/dadu0699/qr-code",
    "color": {
        "dark": "#FFF",
        "light": "#000"
    }
}

### SAVE the id of the created product
@svg  = {{ qrSVG.response.body }}
